### ISSUE TITLE
Fix makefiles so that 'file truncated' error does not happen

### ISSUE THREAD

**Issue by gentoobionic** [gentoobionic/bionic#10]

**Comment by gentoobionic** [comment]
./libc/libc.so: file not recognized: File truncated
collect2: ld returned 1 exit status
make: **\* [libm/libm.so] Error 1
make: **\* Waiting for unfinished jobs....
./libc//libc.so: file not recognized: File truncated
collect2: ld returned 1 exit status
make: **\* [libstdc++/libstdc++.so] Error 1
././libc/bionic//dlmalloc.o: In function `mmap_resize':
dlmalloc.c:(.text+0x988): undefined reference to`mremap'
././libc/bionic//dlmalloc.o: In function `release_unused_segments':
dlmalloc.c:(.text+0x24e9): undefined reference to`munmap'
././libc/bionic//dlmalloc.o: In function `sys_trim':
dlmalloc.c:(.text+0x2886): undefined reference to`mremap'
dlmalloc.c:(.text+0x28a2): undefined reference to `munmap'
././libc/bionic//dlmalloc.o: In function`dlfree':
dlmalloc.c:(.text+0x4a53): undefined reference to `munmap'
././libc/bionic//malloc_debug_common.o: In function`malloc_init_impl':
malloc_debug_common.c:(.text+0xacd): undefined reference to `getpid'
././libc/bionic//pthread_debug.o: In function`debug_realloc':
pthread_debug.c:(.text+0x501): undefined reference to `munmap'
././libc/bionic//pthread_debug.o: In function`traverseTree':
pthread_debug.c:(.text+0x8ee): undefined reference to `gettid'
pthread_debug.c:(.text+0x903): undefined reference to`getpid'
pthread_debug.c:(.text+0x948): undefined reference to `gettid'
pthread_debug.c:(.text+0x94f): undefined reference to`getpid'
pthread_debug.c:(.text+0xa18): undefined reference to `gettid'
././libc/bionic//pthread_debug.o: In function`mutex_lock_checked':
pthread_debug.c:(.text+0xc14): undefined reference to `gettid'
././libc/bionic//pthread_debug.o: In function`mutex_unlock_checked':
pthread_debug.c:(.text+0xd89): undefined reference to `gettid'
././libc/bionic//pthread_debug.o: In function`push_most_recently_locked':
pthread_debug.c:(.text+0x10fd): undefined reference to `gettid'
././libc/bionic//pthread_debug.o: In function`remove_most_recently_locked':
pthread_debug.c:(.text+0x1144): undefined reference to `gettid'
././libc/bionic//pthread_debug.o:pthread_debug.c:(.text+0x11b5): more undefined references to`gettid' follow
././libc/bionic//pthread_debug.o: In function `pthread_debug_init':
pthread_debug.c:(.text+0x1219): undefined reference to`getpid'
././libc/bionic//pthread_debug.o: In function `pthread_debug_mutex_lock_check':
pthread_debug.c:(.text+0x1287): undefined reference to`gettid'
././libc/bionic//pthread_debug.o: In function `pthread_debug_mutex_unlock_check':
pthread_debug.c:(.text+0x12f1): undefined reference to`gettid'
././libc/unistd//sysconf-dynamic.o: In function `line_parser_getc':
sysconf-dynamic.c:(.text+0x3c5): undefined reference to`read'
././libc/unistd//sysconf-dynamic.o: In function `line_parser_gets':
sysconf-dynamic.c:(.text+0x44a): undefined reference to`close'
././libc/unistd//sysconf-dynamic.o: In function `line_parser_done':
sysconf-dynamic.c:(.text+0x4a7): undefined reference to`close'
././libc/bionic//pthread-dynamic.o: In function `_init_thread':
pthread-dynamic.c:(.text+0x44b): undefined reference to`sched_setscheduler'
././libc/bionic//pthread-dynamic.o: In function `mkstack':
pthread-dynamic.c:(.text+0x4fa): undefined reference to`mprotect'
pthread-dynamic.c:(.text+0x510): undefined reference to `munmap'
././libc/bionic//pthread-dynamic.o: In function`pthread_create':
pthread-dynamic.c:(.text+0x666): undefined reference to `munmap'
././libc/bionic//pthread-dynamic.o: In function`pthread_exit':
pthread-dynamic.c:(.text+0xb63): undefined reference to `sigprocmask'
pthread-dynamic.c:(.text+0xb74): undefined reference to`_exit_thread'
././libc/bionic//pthread-dynamic.o: In function `pthread_getschedparam':
pthread-dynamic.c:(.text+0xdda): undefined reference to`sched_getparam'
pthread-dynamic.c:(.text+0xdf1): undefined reference to `sched_getscheduler'
././libc/bionic//pthread-dynamic.o: In function`pthread_setschedparam':
pthread-dynamic.c:(.text+0xe53): undefined reference to `sched_setscheduler'
././libc/bionic//pthread-dynamic.o: In function`__timespec_to_absolute':
pthread-dynamic.c:(.text+0x176d): undefined reference to `clock_gettime'
././libc/bionic//pthread-dynamic.o: In function`__timespec_to_relative_msec':
pthread-dynamic.c:(.text+0x1805): undefined reference to `clock_gettime'
././libc/bionic//pthread-dynamic.o: In function`pthread_kill':
pthread-dynamic.c:(.text+0x25c3): undefined reference to `getpid'
pthread-dynamic.c:(.text+0x25d6): undefined reference to`tgkill'
././libc/bionic//pthread-dynamic.o: In function `pthread_sigmask':
pthread-dynamic.c:(.text+0x2677): undefined reference to`__rt_sigprocmask'
././libc/bionic//pthread-dynamic.o: In function `pthread_setname_np':
pthread-dynamic.c:(.text+0x288c): undefined reference to`prctl'
pthread-dynamic.c:(.text+0x2914): undefined reference to `write'
pthread-dynamic.c:(.text+0x293a): undefined reference to`close'
././libc/unistd//abort.o: In function `abort':
abort.c:(.text+0x13b): undefined reference to`sigprocmask'
abort.c:(.text+0x197): undefined reference to `getpid'
abort.c:(.text+0x1a7): undefined reference to`kill'
abort.c:(.text+0x1dd): undefined reference to `sigaction'
abort.c:(.text+0x1f8): undefined reference to`sigprocmask'
abort.c:(.text+0x1fd): undefined reference to `getpid'
abort.c:(.text+0x20d): undefined reference to`kill'
abort.c:(.text+0x219): undefined reference to `_exit'
././libc/unistd//alarm.o: In function`alarm':
alarm.c:(.text+0x54): undefined reference to `setitimer'
././libc/unistd//brk.o: In function`brk':
brk.c:(.text+0x19): undefined reference to `__brk'
././libc/unistd//daemon.o: In function`daemon':
daemon.c:(.text+0x22): undefined reference to `chdir'
daemon.c:(.text+0x76): undefined reference to`dup2'
daemon.c:(.text+0x8d): undefined reference to `dup2'
daemon.c:(.text+0xa4): undefined reference to`dup2'
daemon.c:(.text+0xb3): undefined reference to `close'
daemon.c:(.text+0xc5): undefined reference to`close'
daemon.c:(.text+0xec): undefined reference to `_exit'
daemon.c:(.text+0xf1): undefined reference to`setsid'
././libc/unistd//eventfd.o: In function `eventfd_read':
eventfd.c:(.text+0x28): undefined reference to`read'
././libc/unistd//eventfd.o: In function `eventfd_write':
eventfd.c:(.text+0x7b): undefined reference to`write'
././libc/unistd//exec.o: In function `execl':
exec.c:(.text+0xc4): undefined reference to`execve'
././libc/unistd//exec.o: In function `execle':
exec.c:(.text+0x19a): undefined reference to`execve'
././libc/unistd//exec.o: In function `execv':
exec.c:(.text+0x290): undefined reference to`execve'
././libc/unistd//exec.o: In function `execvp':
exec.c:(.text+0x44d): undefined reference to`writev'
exec.c:(.text+0x4d0): undefined reference to `execve'
././libc/unistd//exec.o: In function`.L38':
exec.c:(.text+0x598): undefined reference to `execve'
././libc/unistd//fcntl.o: In function`fcntl':
fcntl.c:(.text+0x3b): undefined reference to `__fcntl64'
././libc/unistd//fstatfs.o: In function`fstatfs':
fstatfs.c:(.text+0x28): undefined reference to `__fstatfs64'
././libc/unistd//ftime.o: In function`ftime':
ftime.c:(.text+0x20): undefined reference to `gettimeofday'
././libc/unistd//ftok.o: In function`ftok':
ftok.c:(.text+0x20): undefined reference to `lstat'
././libc/unistd//getcwd.o: In function`getcwd':
getcwd.c:(.text+0x3e): undefined reference to `__getcwd'
././libc/unistd//getdtablesize.o: In function`getdtablesize':
getdtablesize.c:(.text+0x21): undefined reference to `getrlimit'
././libc/unistd//gethostname.o: In function`gethostname':
gethostname.c:(.text+0x26): undefined reference to `uname'
././libc/unistd//getlogin.o: In function`getlogin':
getlogin.c:(.text+0x4f): undefined reference to `fstat'
getlogin.c:(.text+0x96): undefined reference to`close'
././libc/unistd//getpgrp.o: In function `getpgrp':
getpgrp.c:(.text+0x1a): undefined reference to`getpgid'
././libc/unistd//getpriority.o: In function `getpriority':
getpriority.c:(.text+0x20): undefined reference to`__getpriority'
././libc/unistd//initgroups.o: In function `initgroups':
initgroups.c:(.text+0x9a): undefined reference to`setgroups'
././libc/unistd//killpg.o: In function `killpg':
killpg.c:(.text+0x3c): undefined reference to`kill'
././libc/unistd//lseek64.o: In function `lseek64':
lseek64.c:(.text+0x4b): undefined reference to`__llseek'
././libc/unistd//mmap.o: In function `mmap':
mmap.c:(.text+0x5d): undefined reference to`__mmap2'
mmap.c:(.text+0x8a): undefined reference to `madvise'
././libc/unistd//nice.o: In function`nice':
nice.c:(.text+0x46): undefined reference to `setpriority'
././libc/unistd//open.o: In function`open':
open.c:(.text+0x54): undefined reference to `__open'
././libc/unistd//openat.o: In function`openat':
openat.c:(.text+0x5b): undefined reference to `__openat'
././libc/unistd//opendir.o: In function`_readdir_unlocked':
opendir.c:(.text+0x13f): undefined reference to `getdents'
././libc/unistd//opendir.o: In function`closedir':
opendir.c:(.text+0x367): undefined reference to `close'
././libc/unistd//opendir.o: In function`rewinddir':
opendir.c:(.text+0x3d2): undefined reference to `lseek'
././libc/unistd//openpty.o: In function`openpty':
openpty.c:(.text+0x184): undefined reference to `close'
openpty.c:(.text+0x1a1): undefined reference to`close'
././libc/unistd//perror.o: In function `perror':
perror.c:(.text+0x5a): undefined reference to`write'
perror.c:(.text+0x78): undefined reference to `write'
perror.c:(.text+0xa0): undefined reference to`write'
perror.c:(.text+0xbe): undefined reference to `write'
././libc/unistd//popen.o: In function`popen':
popen.c:(.text+0x8f): undefined reference to `pipe'
popen.c:(.text+0xcc): undefined reference to`close'
popen.c:(.text+0xd7): undefined reference to `close'
popen.c:(.text+0x126): undefined reference to`close'
popen.c:(.text+0x149): undefined reference to `close'
popen.c:(.text+0x164): undefined reference to`dup2'
popen.c:(.text+0x16f): undefined reference to `close'
popen.c:(.text+0x17c): undefined reference to`close'
popen.c:(.text+0x196): undefined reference to `dup2'
popen.c:(.text+0x1a1): undefined reference to`close'
popen.c:(.text+0x1c8): undefined reference to `execve'
popen.c:(.text+0x1d4): undefined reference to`_exit'
popen.c:(.text+0x1fe): undefined reference to `close'
popen.c:(.text+0x220): undefined reference to`close'
././libc/unistd//pread.o: In function `pread':
pread.c:(.text+0x37): undefined reference to`pread64'
././libc/unistd//pselect.o: In function `pselect':
pselect.c:(.text+0xb4): undefined reference to`select'
././libc/unistd//pwrite.o: In function `pwrite':
pwrite.c:(.text+0x37): undefined reference to`pwrite64'
././libc/unistd//raise.o: In function `raise':
raise.c:(.text+0x13): undefined reference to`gettid'
raise.c:(.text+0x22): undefined reference to `kill'
././libc/unistd//reboot.o: In function`reboot':
reboot.c:(.text+0x31): undefined reference to `__reboot'
././libc/unistd//recv.o: In function`recv':
recv.c:(.text+0x3e): undefined reference to `recvfrom'
././libc/unistd//sbrk.o: In function`sbrk':
sbrk.c:(.text+0x26): undefined reference to `__brk'
sbrk.c:(.text+0x55): undefined reference to`__brk'
././libc/unistd//send.o: In function `send':
send.c:(.text+0x3e): undefined reference to`sendto'
././libc/unistd//setegid.o: In function `setegid':
setegid.c:(.text+0x29): undefined reference to`setresgid'
././libc/unistd//setuid.o: In function `setuid':
setuid.c:(.text+0x24): undefined reference to`__setuid'
././libc/unistd//seteuid.o: In function `seteuid':
seteuid.c:(.text+0x34): undefined reference to`__setresuid'
././libc/unistd//setreuid.o: In function `setreuid':
setreuid.c:(.text+0x2b): undefined reference to`__setreuid'
././libc/unistd//setresuid.o: In function `setresuid':
setresuid.c:(.text+0x32): undefined reference to`__setresuid'
././libc/unistd//setpgrp.o: In function `setpgrp':
setpgrp.c:(.text+0x22): undefined reference to`setpgid'
././libc/unistd//sigblock.o: In function `sigblock':
sigblock.c:(.text+0x71): undefined reference to`sigprocmask'
././libc/unistd//siginterrupt.o: In function `siginterrupt':
siginterrupt.c:(.text+0x28): undefined reference to`sigaction'
siginterrupt.c:(.text+0x60): undefined reference to `sigaction'
././libc/unistd//signal.o: In function`_signal':
signal.c:(.text+0x80): undefined reference to `sigaction'
././libc/unistd//sigsetmask.o: In function`sigsetmask':
sigsetmask.c:(.text+0x71): undefined reference to `sigprocmask'
././libc/unistd//sigsuspend.o: In function`sigsuspend':
sigsuspend.c:(.text+0x34): undefined reference to `__sigsuspend'
././libc/unistd//sigwait.o: In function`sigwait':
sigwait.c:(.text+0x49): undefined reference to `__rt_sigtimedwait'
././libc/unistd//sleep.o: In function`sleep':
sleep.c:(.text+0x3b): undefined reference to `nanosleep'
././libc/unistd//statfs.o: In function`statfs':
statfs.c:(.text+0x28): undefined reference to `__statfs64'
././libc/unistd//syslog.o: In function`vsyslog_r':
syslog.c:(.text+0x369): undefined reference to `getpid'
syslog.c:(.text+0x5d8): undefined reference to`writev'
syslog.c:(.text+0x761): undefined reference to `writev'
syslog.c:(.text+0x76c): undefined reference to`close'
././libc/unistd//syslog.o: In function `disconnectlog_r':
syslog.c:(.text+0x7b8): undefined reference to`close'
././libc/unistd//syslog.o: In function `connectlog_r':
syslog.c:(.text+0x80c): undefined reference to`socket'
syslog.c:(.text+0x8b5): undefined reference to `connect'
syslog.c:(.text+0x8c7): undefined reference to`close'
././libc/unistd//syslog.o: In function `closelog_r':
syslog.c:(.text+0x964): undefined reference to`close'
././libc/unistd//system.o: In function `system':
system.c:(.text+0x118): undefined reference to`sigprocmask'
system.c:(.text+0x149): undefined reference to `sigprocmask'
system.c:(.text+0x16e): undefined reference to`sigprocmask'
system.c:(.text+0x18f): undefined reference to `execve'
system.c:(.text+0x19b): undefined reference to`_exit'
system.c:(.text+0x201): undefined reference to `sigprocmask'
././libc/unistd//time.o: In function`time':
time.c:(.text+0x21): undefined reference to `gettimeofday'
././libc/unistd//time.o: In function`clock_now':
time.c:(.text+0x70): undefined reference to `clock_gettime'
././libc/unistd//ttyname.o: In function`ttyname':
ttyname.c:(.text+0x2d): undefined reference to `getpid'
ttyname.c:(.text+0xae): undefined reference to`readlink'
ttyname.c:(.text+0xf9): undefined reference to `close'
././libc/unistd//umount.o: In function`umount':
umount.c:(.text+0x21): undefined reference to `umount2'
././libc/unistd//usleep.o: In function`usleep':
usleep.c:(.text+0x61): undefined reference to `nanosleep'
././libc/unistd//wait.o: In function`wait':
wait.c:(.text+0x31): undefined reference to `__wait4'
././libc/unistd//wait.o: In function`wait3':
wait.c:(.text+0x6a): undefined reference to `__wait4'
././libc/unistd//wait.o: In function`waitpid':
wait.c:(.text+0xa3): undefined reference to `__wait4'
././libc/unistd//wait.o: In function`waitid':
wait.c:(.text+0xe3): undefined reference to `__waitid'
././libc/stdio//freopen.o: In function`freopen':
freopen.c:(.text+0x2ab): undefined reference to `dup2'
freopen.c:(.text+0x2ba): undefined reference to`close'
././libc/stdio//fseek.o: In function `fseeko':
fseek.c:(.text+0x202): undefined reference to`fstat'
fseek.c:(.text+0x270): undefined reference to `fstat'
././libc/stdio//makebuf.o: In function`__swhatbuf':
makebuf.c:(.text+0x147): undefined reference to `fstat'
././libc/stdio//mktemp.o: In function`_gettemp':
mktemp.c:(.text+0x170): undefined reference to `getpid'
mktemp.c:(.text+0x279): undefined reference to`stat'
mktemp.c:(.text+0x328): undefined reference to `mkdir'
mktemp.c:(.text+0x35e): undefined reference to`lstat'
././libc/stdio//remove.o: In function `remove':
remove.c:(.text+0x20): undefined reference to`lstat'
remove.c:(.text+0x45): undefined reference to `rmdir'
remove.c:(.text+0x52): undefined reference to`unlink'
././libc/stdio//stdio.o: In function `__sread':
stdio.c:(.text+0x32): undefined reference to`read'
././libc/stdio//stdio.o: In function `__swrite':
stdio.c:(.text+0xb3): undefined reference to`lseek'
stdio.c:(.text+0xe4): undefined reference to `write'
././libc/stdio//stdio.o: In function`__sseek':
stdio.c:(.text+0x120): undefined reference to `lseek'
././libc/stdio//stdio.o: In function`__sclose':
stdio.c:(.text+0x185): undefined reference to `close'
././libc/stdio//tmpfile.o: In function`tmpfile':
tmpfile.c:(.text+0xa8): undefined reference to `sigprocmask'
tmpfile.c:(.text+0xc7): undefined reference to`unlink'
tmpfile.c:(.text+0xd3): undefined reference to `umask'
tmpfile.c:(.text+0xe3): undefined reference to`umask'
tmpfile.c:(.text+0x100): undefined reference to `fchmod'
tmpfile.c:(.text+0x11b): undefined reference to`sigprocmask'
tmpfile.c:(.text+0x15b): undefined reference to `close'
././libc/stdio//vfprintf.o: In function`.L26':
vfprintf.c:(.text+0x2788): undefined reference to `munmap'
././libc/stdio//vfprintf.o: In function`.L551':
vfprintf.c:(.text+0x3635): undefined reference to `munmap'
././libc/stdio//vfprintf.o: In function`__grow_type_table':
vfprintf.c:(.text+0x3738): undefined reference to `munmap'
././libc/stdlib//atexit.o: In function`__cxa_atexit':
atexit.c:(.text+0x91): undefined reference to `mprotect'
atexit.c:(.text+0x1cd): undefined reference to`mprotect'
././libc/stdlib//atexit.o: In function `__cxa_finalize':
atexit.c:(.text+0x2d6): undefined reference to`mprotect'
atexit.c:(.text+0x30f): undefined reference to `mprotect'
atexit.c:(.text+0x399): undefined reference to`munmap'
././libc/stdlib//atexit.o: In function `__atexit_register_cleanup':
atexit.c:(.text+0x4c9): undefined reference to`mprotect'
atexit.c:(.text+0x504): undefined reference to `mprotect'
././libc/stdlib//exit.o: In function`exit':
exit.c:(.text+0x25): undefined reference to `_exit'
././libc/stdlib//setjmperr.o: In function`longjmperror':
setjmperr.c:(.text+0x2c): undefined reference to `write'
././libc/inet//bindresvport.o: In function`bindresvport':
bindresvport.c:(.text+0x72): undefined reference to `getpid'
bindresvport.c:(.text+0x10f): undefined reference to`bind'
././libc/tzcode//localtime.o: In function `tzload':
localtime.c:(.text+0x421): undefined reference to`access'
localtime.c:(.text+0x502): undefined reference to `read'
localtime.c:(.text+0x516): undefined reference to`close'
localtime.c:(.text+0x563): undefined reference to `lseek'
localtime.c:(.text+0x58a): undefined reference to`read'
localtime.c:(.text+0x598): undefined reference to `close'
././libc/bionic//cpuacct.o: In function`cpuacct_add':
cpuacct.c:(.text+0x81): undefined reference to `mkdir'
cpuacct.c:(.text+0xed): undefined reference to`write'
cpuacct.c:(.text+0x134): undefined reference to `close'
././libc/bionic//arc4random.o: In function`arc4_stir':
arc4random.c:(.text+0x18b): undefined reference to `read'
arc4random.c:(.text+0x196): undefined reference to`close'
arc4random.c:(.text+0x1ae): undefined reference to `gettimeofday'
arc4random.c:(.text+0x1b3): undefined reference to`getpid'
././libc/bionic//arc4random.o: In function `arc4random':
arc4random.c:(.text+0x41a): undefined reference to`getpid'
././libc/bionic//arc4random.o: In function `arc4random_buf':
arc4random.c:(.text+0x47e): undefined reference to`getpid'
././libc/bionic//fdprintf.o: In function `vfdprintf':
fdprintf.c:(.text+0x50): undefined reference to`write'
././libc/bionic//fork.o: In function `fork':
fork.c:(.text+0x25): undefined reference to`__fork'
fork.c:(.text+0x46): undefined reference to `gettid'
fork.c:(.text+0x5e): undefined reference to`getuid'
././libc/bionic//fts.o: In function `fts_close':
fts.c:(.text+0x4de): undefined reference to`fchdir'
fts.c:(.text+0x4f6): undefined reference to `close'
././libc/bionic//fts.o: In function`fts_read':
fts.c:(.text+0x6a1): undefined reference to `close'
fts.c:(.text+0x83f): undefined reference to`fchdir'
fts.c:(.text+0xa48): undefined reference to `fchdir'
fts.c:(.text+0xa9f): undefined reference to`fchdir'
fts.c:(.text+0xabb): undefined reference to `close'
fts.c:(.text+0xaf6): undefined reference to`close'
././libc/bionic//fts.o: In function `fts_children':
fts.c:(.text+0xd47): undefined reference to`fchdir'
fts.c:(.text+0xd56): undefined reference to `close'
fts.c:(.text+0xd68): undefined reference to`close'
././libc/bionic//fts.o: In function `fts_build':
fts.c:(.text+0x136b): undefined reference to`fchdir'
././libc/bionic//fts.o: In function `fts_stat':
fts.c:(.text+0x1477): undefined reference to`stat'
fts.c:(.text+0x149e): undefined reference to `lstat'
fts.c:(.text+0x14d7): undefined reference to`lstat'
././libc/bionic//fts.o: In function `fts_safe_changedir':
fts.c:(.text+0x1ac5): undefined reference to`fstat'
fts.c:(.text+0x1b32): undefined reference to `fchdir'
fts.c:(.text+0x1b50): undefined reference to`close'
././libc/bionic//if_nametoindex.o: In function `if_nametoindex':
if_nametoindex.c:(.text+0x6a): undefined reference to`socket'
if_nametoindex.c:(.text+0xa2): undefined reference to `close'
././libc/bionic//if_indextoname.o: In function`if_indextoname':
if_indextoname.c:(.text+0x52): undefined reference to `socket'
if_indextoname.c:(.text+0xba): undefined reference to`close'
././libc/bionic//ioctl.o: In function `ioctl':
ioctl.c:(.text+0x3b): undefined reference to`__ioctl'
././libc/bionic//libc_init_common.o: In function `__libc_init_tls':
libc_init_common.c:(.text+0x63): undefined reference to`gettid'
././libc/bionic//logd_write.o: In function `__write_to_log_kernel':
logd_write.c:(.text+0x70): undefined reference to`writev'
././libc/bionic//realpath.o: In function `realpath':
realpath.c:(.text+0x3d7): undefined reference to`lstat'
realpath.c:(.text+0x47f): undefined reference to `readlink'
././libc/bionic//sched_getaffinity.o: In function`sched_getaffinity':
sched_getaffinity.c:(.text+0x27): undefined reference to `__sched_getaffinity'
././libc/bionic//sched_getcpu.o: In function`sched_getcpu':
sched_getcpu.c:(.text+0x29): undefined reference to `__getcpu'
././libc/bionic//semaphore.o: In function`sem_timedwait':
semaphore.c:(.text+0x41f): undefined reference to `clock_gettime'
././libc/bionic//ssp.o: In function`__guard_setup':
ssp.c:(.text+0x120): undefined reference to `read'
ssp.c:(.text+0x12e): undefined reference to`close'
././libc/bionic//ssp.o: In function `__stack_chk_fail':
ssp.c:(.text+0x1b8): undefined reference to`sigprocmask'
ssp.c:(.text+0x1d8): undefined reference to `readlink'
ssp.c:(.text+0x279): undefined reference to`sigaction'
ssp.c:(.text+0x27e): undefined reference to `getpid'
ssp.c:(.text+0x28e): undefined reference to`kill'
ssp.c:(.text+0x29a): undefined reference to `_exit'
././libc/bionic//system_properties.o: In function`__system_properties_init':
system_properties.c:(.text+0xfe): undefined reference to `munmap'
././libc/bionic//system_properties.o: In function`send_prop_msg':
system_properties.c:(.text+0x33b): undefined reference to `socket'
system_properties.c:(.text+0x3c2): undefined reference to`connect'
system_properties.c:(.text+0x3ec): undefined reference to `close'
system_properties.c:(.text+0x461): undefined reference to`poll'
system_properties.c:(.text+0x4a9): undefined reference to `close'
././libc/bionic//utime.o: In function`utime':
utime.c:(.text+0x53): undefined reference to `utimes'
././libc/netbsd/isc//ev_timers.o: In function`__evNowTime':
ev_timers.c:(.text+0x15c): undefined reference to `clock_gettime'
ev_timers.c:(.text+0x180): undefined reference to`gettimeofday'
././libc/netbsd/isc//ev_timers.o: In function `__evUTCTime':
ev_timers.c:(.text+0x1f1): undefined reference to`clock_gettime'
ev_timers.c:(.text+0x215): undefined reference to `gettimeofday'
././libc/netbsd/resolv//herror.o: In function`herror':
herror.c:(.text+0x16f): undefined reference to `writev'
././libc/netbsd/resolv//res_init.o: In function`__res_vinit':
res_init.c:(.text+0x15e): undefined reference to `getpid'
././libc/netbsd/resolv//res_init.o: In function`real_randomid':
res_init.c:(.text+0x13d3): undefined reference to `read'
res_init.c:(.text+0x13f4): undefined reference to`close'
res_init.c:(.text+0x1425): undefined reference to `close'
././libc/netbsd/resolv//res_init.o: In function`__res_randomid':
res_init.c:(.text+0x147d): undefined reference to `gettimeofday'
res_init.c:(.text+0x148c): undefined reference to`getpid'
././libc/netbsd/resolv//res_init.o: In function `__res_nclose':
res_init.c:(.text+0x14ca): undefined reference to`close'
res_init.c:(.text+0x151e): undefined reference to `close'
././libc/netbsd/resolv//res_send.o: In function`random_bind':
res_send.c:(.text+0x11c): undefined reference to `bind'
res_send.c:(.text+0x162): undefined reference to`bind'
././libc/netbsd/resolv//res_send.o: In function `__res_nsend':
res_send.c:(.text+0x7ef): undefined reference to`getpeername'
././libc/netbsd/resolv//res_send.o: In function `send_vc':
res_send.c:(.text+0x1113): undefined reference to`getpeername'
res_send.c:(.text+0x11ac): undefined reference to `socket'
res_send.c:(.text+0x147d): undefined reference to`writev'
res_send.c:(.text+0x1527): undefined reference to `read'
res_send.c:(.text+0x16c5): undefined reference to`read'
res_send.c:(.text+0x1784): undefined reference to `read'
././libc/netbsd/resolv//res_send.o: In function`connect_with_timeout':
res_send.c:(.text+0x18b0): undefined reference to `connect'
././libc/netbsd/resolv//res_send.o: In function`retrying_select':
res_send.c:(.text+0x1bc2): undefined reference to `getsockopt'
././libc/netbsd/resolv//res_send.o: In function`send_dg':
res_send.c:(.text+0x1c68): undefined reference to `socket'
res_send.c:(.text+0x1dea): undefined reference to`connect'
res_send.c:(.text+0x207b): undefined reference to `recvfrom'
././libc/netbsd/resolv//res_cache.o: In function`_time_now':
res_cache.c:(.text+0x21): undefined reference to `gettimeofday'
././libc/netbsd/net//getaddrinfo.o: In function`_test_connect':
getaddrinfo.c:(.text+0x184): undefined reference to `socket'
getaddrinfo.c:(.text+0x1ad): undefined reference to`connect'
getaddrinfo.c:(.text+0x1da): undefined reference to `close'
././libc/netbsd/net//getaddrinfo.o: In function`android_getaddrinfo_proxy':
getaddrinfo.c:(.text+0x358): undefined reference to `getpid'
getaddrinfo.c:(.text+0x420): undefined reference to`socket'
getaddrinfo.c:(.text+0x45d): undefined reference to `setsockopt'
getaddrinfo.c:(.text+0x4c4): undefined reference to`connect'
getaddrinfo.c:(.text+0x4eb): undefined reference to `close'
././libc/netbsd/net//getaddrinfo.o: In function`explore_null':
getaddrinfo.c:(.text+0x1294): undefined reference to `socket'
getaddrinfo.c:(.text+0x12be): undefined reference to`close'
././libc/netbsd/net//getaddrinfo.o: In function `_find_src_addr':
getaddrinfo.c:(.text+0x2f75): undefined reference to`socket'
getaddrinfo.c:(.text+0x2fb7): undefined reference to `connect'
getaddrinfo.c:(.text+0x2fdd): undefined reference to`close'
getaddrinfo.c:(.text+0x2ffd): undefined reference to `getsockname'
getaddrinfo.c:(.text+0x300d): undefined reference to`close'
getaddrinfo.c:(.text+0x301f): undefined reference to `close'
././libc/netbsd/net//getaddrinfo.o: In function`_using_alt_dns':
getaddrinfo.c:(.text+0x3219): undefined reference to `getpid'
././libc/netbsd/net//getnameinfo.o: In function`android_gethostbyaddr_proxy':
getnameinfo.c:(.text+0xbd): undefined reference to `getpid'
getnameinfo.c:(.text+0x123): undefined reference to`socket'
getnameinfo.c:(.text+0x160): undefined reference to `setsockopt'
getnameinfo.c:(.text+0x1c7): undefined reference to`connect'
getnameinfo.c:(.text+0x1ee): undefined reference to `close'
././libc/mntent//addmntent.o: In function`addmntent':
addmntent.c:(.text+0x26e): undefined reference to `ftruncate'
././libc/arch-x86/bionic//__set_tls.o: In function`__set_tls':
__set_tls.c:(.text+0x3b): undefined reference to `__set_thread_area'
././libc/bionic//pthread-timers.o: In function`timer_create':
pthread-timers.c:(.text+0x5c5): undefined reference to `__timer_create'
pthread-timers.c:(.text+0x5fb): undefined reference to`clock_gettime'
././libc/bionic//pthread-timers.o: In function `timer_delete':
pthread-timers.c:(.text+0x7cd): undefined reference to`__timer_delete'
././libc/bionic//pthread-timers.o: In function `timer_gettime_internal':
pthread-timers.c:(.text+0x88a): undefined reference to`clock_gettime'
././libc/bionic//pthread-timers.o: In function `timer_gettime':
pthread-timers.c:(.text+0x924): undefined reference to`__timer_gettime'
././libc/bionic//pthread-timers.o: In function `timer_settime':
pthread-timers.c:(.text+0x9d8): undefined reference to`__timer_settime'
pthread-timers.c:(.text+0xa5c): undefined reference to `clock_gettime'
././libc/bionic//pthread-timers.o: In function`timer_getoverrun':
pthread-timers.c:(.text+0xb09): undefined reference to `__timer_getoverrun'
././libc/bionic//pthread-timers.o: In function`timer_thread_start':
pthread-timers.c:(.text+0xbea): undefined reference to `clock_gettime'
././libc/bionic//ptrace.o: In function`ptrace':
ptrace.c:(.text+0x39): undefined reference to `__ptrace'
ptrace.c:(.text+0x6e): undefined reference to`__ptrace'
/Users/Gentoo/usr/libexec/gcc/i686-pc-linux-gnu/ld: warning: creating a DT_TEXTREL in object.
collect2: ld returned 1 exit status
make: **\* [libc/libc.so] Error 1

**Comment by gentoobionic** [comment]
subsequent make works fine

**Comment by cfriedt** [comment]
Fixed on or before latest major commit
