### ISSUE TITLE
Fix / verify .so linkage with crt*.o files

### ISSUE THREAD

**Issue by gentoobionic** [gentoobionic/bionic#12]
verify linkage entirely, using custom linker rules in Makefile.am
- see http://dev.gentoo.org/~vapier/crt.txt
- that means, I should be able to drop it in my /usr/i686-pc-linux-bionic chroot
   and it should Just Work (TM)
- specifically, when building .so's, the order of the crt*.o files must be specified for the binary to function properly

**Comment by cfriedt** [comment]
Fixed in latest major commit
