### ISSUE TITLE
Add header install targets

### ISSUE THREAD

**Issue by gentoobionic** [gentoobionic/bionic#14]
Headers should also be installed to their respective (w.r.t. DESTDIR, prefix) locations.

The kernel header should _not_ be installed in this stage, or it should be optional. This is so that e.g. Gentoo's sys-kernel/bionic-kernel-headers still works.

**Comment by cfriedt** [comment]
Working on this this weekend. Might have to look in more detail at autoconf / configure output variables, and also zoneinfo install target, to see if I can use a specific variable for that

**Comment by gentoobionic** [comment]
Fixed in commit 3f15dba
