### ISSUE TITLE
libgcc_shared_fake directory missing

### ISSUE THREAD

**Issue by steev** [gentoobionic/bionic#2]
autogen.sh fails because it cannot find libgcc_shared_fake/Makefile.in

**Comment by cfriedt** [comment]
Hi Steev - I noticed that too almost immediately after committing. The line should be removed from configure.ac. Feel free to commit the change!

**Comment by steev** [comment]
Committed!  Hopefully I'll get this built soon, and can start helping out

**Comment by cfriedt** [comment]
Hey Steev, 

Feel free to add your change to the ChangeLog file, re-run "sh update-authors.sh", and commit the resulting changes too!

**Comment by steev** [comment]
The ChangeLog file is currently 0 size, so that's why I didn't add an
entry.  Do you have a preferred format?

**Comment by cfriedt** [comment]
Yep - the format is like this (pulled from my fb4j repo). Gmail
replaced tabs with spaces, so I inserted \t where a tab should go.

2013-12-31\tChristopher Friedt\tchrisfriedt@gmail.com
\t\* initial check-in, set version to 0.1
\t\* updated README, COPYING
\t\* added TestFB4J.java to src/test
